import { App } from './environment.types';

export enum TransporterProviders {
  AUTH_SERVICE = 'AUTH_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  PROMO_SERVICE = 'PROMO_SERVICE',
  PAYMENT_SERVICE = 'PAYMENT_SERVICE',
  NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
  WALLET_SERVICE = 'WALLET_SERVICE',
  RE_GAMEPLAY_SERVICE = 'RE_GAMEPLAY_SERVICE',
  SP_GAMEPLAY_SERVICE = 'SP_GAMEPLAY_SERVICE',
  LUDO_GAMEPLAY_SERVICE = 'LUDO_GAMEPLAY_SERVICE',
  SCHEDULER_SERVICE = 'SCHEDULER_SERVICE',
  SOCKET_GATEWAY_SERVICE = 'SOCKET_GATEWAY_SERVICE',
  CBR_GAMEPLAY_SERVICE = 'CBR_GAMEPLAY_SERVICE',
  LUDO_TOURNAMENT_SERVICE = 'LUDO_TOURNAMENT_SERVICE',
  LUDO_MEGA_TOURNAMENT_SERVICE = 'LUDO_MEGA_TOURNAMENT_SERVICE',
  RECORD_SERVICE = 'RECORD_SERVICE',
  SL_GAMEPLAY_SERVICE = 'SL_GAMEPLAY_SERVICE',
  EPL_GAMEPLAY_SERVICE = 'EPL_GAMEPLAY_SERVICE',
  AVIATOR_GAMEPLAY_SERVICE = 'AVIATOR_GAMEPLAY_SERVICE',
}

export enum TransporterCmds {
  // User Service
  CREATE_OR_UPDATE_USER = 'USERS/CREATE_OR_UPDATE_USER',
  CHECK_IF_FIRST_LOGIN = 'CECHK_IF_FIRST_LOGIN',
  GET_USER = 'USERS/GET_USER',
  UPDATE_USER = 'USERS/UPDATE_USER',
  UPDATE_USER_DEVICE = 'USERS/UPDATE_USER_DEVICE',
  UPLOAD_KYC = 'USERS/UPLOAD_KYC',
  GET_CLIENT_ID = 'USERS/GET_CLIENT_ID',
  KYC_OTP_VERIFY = 'USERS/KYC_OTP_VERIFY',
  CREATE_REFERRAL = 'USERS/CREATE_REFERRAL',
  GET_USER_INFO_FOR_DEPOSIT = 'GET_USER_INFO_FOR_DEPOSIT',
  GET_USER_INFO_FOR_PAYOUT = 'GET_USER_INFO_FOR_PAYOUT',
  GET_USER_PROFILE_PIC_LIST = 'GET_USER_PROFILE_PIC_LIST',
  UPDATE_STATS = 'UPDATE_STATS',

  //promo-service
  REFERRAL_HISTORY = 'PROMO/REFERRAL/HISTORY',
  CREDIT_RERERRAL_BONUS = 'PROMO/CREDIT_REFERRAL_BONUS',
  GET_COUPON_BY_PROMO_CODE = 'PROMO/GET_COUPON_BY_PROMO_CODE',
  CREATE_COUPON = 'PROMO/CREATE_COUPON',
  DELETE_COUPON = 'PROMO/DELETE_COUPON',

  //payment-service
  DEPOSIT_CASHFREE_STATUS = 'DEPOSIT/CASHFREE_STATUS',
  CREATE_DEPOSIT_ORDER = 'PAYMENT/CREATE_DEPOSIT_ORDER',
  CREATE_PAYOUT_ORDER = 'CREATE_PAYOUT_ORDER',
  CONVERT_TO_MAIN = 'CONVERT_TO_MAIN',
  GET_DEPOSIT_HISTORY = 'GET_DEPOSIT_HISTORY',
  GET_PAYOUT_HISTORY = 'GET_PAYOUT_HISTORY',
  DEPOSIT_WEBHOOK = 'DEPOSIT_WEBHHOK',
  JUSPAY_PAYOUT_WEBHOOK = 'JUSPAY_PAYOUT_WEBHOOK',
  CASHFREE_PAYOUT_WEBHOOK = 'CASHFREE_PAYOUT_WEBHOOK',
  GET_CONVERSION_RATE = 'GET_CONVERSION_RATE',
  GENERATE_INVOICE = 'GENERATE_INVOICE',
  MANUALLY_APPROVE_WITHDRAWAL = 'MANUALLY_APPROVE_WITHDRAWAL',
  MANUALLY_REJECT_WITHDRAWAL = 'MANUALLY_REJECT_WITHDRAWAL',
  MANUALLY_VERIFY_WITHDRAWAL = 'MANUALLY_VERIFY_WITHDRAWAL',
  WITHDRAWALS_VERIFIED_ACCOUNTS = 'WITHDRAWALS_VERIFIED_ACCOUNTS',

  // Game-Record
  GET_CBR_GAME_HISTORY = 'GET_CBR_GAME_HISTORY',
  GET_SP_GAME_HISTORY = 'GET_SP_GAME_HISTORY',
  GET_SP_ROUND_HISTORY = 'GET_SP_ROUND_HISTORY',
  GET_RE_GAME_HISTORY = 'GET_RE_GAME_HISTORY',
  GET_RE_ROUND_HISTORY = 'GET_RE_ROUND_HISTORY',
  GET_LUDO_GAME_HISTORY = 'GET_LUDO_GAME_HISTORY',
  GET_AVIATOR_GAME_HISTORY = 'GET_AVIATOR_GAME_HISTORY',
  GET_CBR_SCOREBOARD = 'GET_CBR_SCOREBOARD',
  UPDATE_DAY_LEADERBOARD = 'UPDATE_DAY_LEADERBOARD',
  UPDATE_WEEK_LEADERBOARD = 'UPDATE_WEEK_LEADERBOARD',
  UPDATE_MONTH_LEADERBOARD = 'UPDATE_MONTH_LEADERBOARD',
  GET_LEADERBOARD = 'GET_LEADERBOARD',

  // Notification Service
  SEND_OTP = 'NOTIFICATION/SEND_OTP',
  SEND_DOWNLOAD_LINK_SMS = 'NOTIFICATION/SEND_DOWNLOAD_LINK_SMS',
  SEND_LUDO_TOURNAMENT_NOTIFICATION = 'NOTIFICATION/SEND_LUDO_TOURNAMENT_NOTIFICATION',
  SEND_PUSH_NOTIFICATION = 'NOTIFICATION/SEND_PUSH_NOTIFICATION',
  SEND_MASS_PUSH_NOTIFICATION = 'NOTIFICATION/SEND_MASS_PUSH_NOTIFICATION',
  SEND_APPSFLYER_EVENT = 'NOTIFICATION/SEND_APPSFLYER_EVENT',

  // Auth Service
  INIT_AUTH = 'AUTH/INIT_AUTH',
  VERIFY_AUTH = 'AUTH/VERIFY_AUTH',
  UPDATE_ROLES = 'AUTH/UPDATE_ROLES',

  // Wallet Service
  GET_WALLET = 'GET_WALLET',
  CREDIT_DEPOSIT_TO_WALLET = 'CREDIT_DEPOSIT_TO_WALLET',
  DEBIT_PAYOUT_FROM_WALLET = 'DEBIT_PAYOUT_FROM_WALLET',
  CREDIT_PAYOUT_REFUND_TO_WALLET = 'CREDIT_PAYOUT_REFUND_TO_WALLET',
  CREDIT_SIGNUP_BONUS = 'CREDIT_SIGNUP_BONUS',
  CHECK_WALLET_BALANCE = 'CHECK_WALLET_BALANCE',
  EXPIRE_BONUS = 'EXPIRE_BONUS',
  CBR_CHECK_WALLET_BALANCE = 'CBR_CHECK_WALLET_BALANCE',
  CBR_DEBIT_JOIN_FEE = 'CBR_DEBIT_JOIN_FEE',
  CBR_ADD_WINNING_AMOUNT = 'CBR_ADD_WINNING_AMOUNT',
  GET_CB_LIVE_GAMES = 'GET_CB_LIVE_GAMES',
  LUDO_CHECK_WALLET_BALANCE = 'LUDO_CHECK_WALLET_BALANCE',
  LUDO_DEBIT_JOIN_FEE = 'LUDO_DEBIT_JOIN_FEE',
  LUDO_CREDIT_WIN_AMOUNT = 'LUDO_CREDIT_WIN_AMOUNT',
  LUDO_TOURNAMENT_CREDIT_PRIZE = 'LUDO_TOURNAMENT_CREDIT_PRIZE',
  LUDO_TOURNAMENT_REFUND = 'LUDO_TOURNAMENT_REFUND',
  CREDIT_TAX_REWARD_TO_WALLET = 'CREDIT_TAX_REWARD_TO_WALLET',
  RE_CHECK_WALLET_BALANCE = 'RE_CHECK_WALLET_BALANCE',

  // SP Gameplay
  SP_JOIN_TABLE = 'SP_JOIN_TABLE',
  SP_RECONNECT = 'SP_RECONNECT',
  SP_FORCE_RECONNECT = 'SP_FORCE_RECONNECT',
  SP_HANDLE_TABLE_RESPONSE = 'SP_HANDLE_TABLE_RESPONSE',
  SP_GET_TABLE = 'SP_GET_TABLE',
  SP_GET_PREV_PLAYER_INDEX = 'SP_GET_PREV_PLAYER_INDEX',
  SP_LEAVE_TABLE = 'SP_LEAVE_TABLE',
  SP_ADD_TIMEOUT_ACTION = 'SP_ADD_TIMEOUT_ACTION',
  SP_GET_PLAYER_CARDS_INFO = 'SP_GET_PLAYER_CARDS_INFO',
  SP_UPDATE_TABLE = 'SP_UPDATE_TABLE',
  SP_REMOVE_TABLE = 'SP_REMOVE_TABLE',
  SP_LEAVE_WAITING_TABLE = 'SP_LEAVE_WAITING_TABLE',
  SP_CHECK_WALLET_BALANCE = 'SP_CHECK_WALLET_BALANCE',
  SP_CHECK_DOUBLE_JOIN = 'SP_CHECK_DOUBLE_JOIN',
  SP_ADD_TO_QUEUE = 'SP_ADD_TO_QUEUE',
  SP_CHECK_IF_JOINED = 'SP_CHECK_IF_JOINED',
  SP_CREATE_ROUND_HISTORY = 'SP_CREATE_ROUND_HISTORY',
  SP_DEBIT_JOIN_FEE = 'SP_DEBIT_JOIN_FEE',
  SP_ADD_WINNING_AMOUNT = 'SP_ADD_WINNING_AMOUNT',
  SP_SIDE_SHOW = 'SP_SIDE_SHOW',
  SP_REFUND_INACTIVE_TABLE = 'SP_REFUND_INACTIVE_TABLE',
  SP_CREATE_LEFT_USER_TABLE_HISTORY = 'SP_CREATE_LEFT_USER_TABLE_HISTORY',
  SP_MATCH_GAMES = 'SP_MATCH_GAMES',

  // Rummy Empire Gameplay
  RE_MATCH_GAMES = 'RE_MATCH_GAMES',
  RE_ADD_WINNING_AMOUNT = 'RE_ADD_WINNING_AMOUNT',
  RE_DEBIT_JOIN_FEE = 'RE_DEBIT_JOIN_FEE',
  RE_CHECK_IF_RECONNECTED = 'RE_CHECK_IF_RECONNECTED',
  GET_RE_LIVE_GAMES = 'GET_RE_LIVE_GAMES',
  CLEAR_RE_STUCK_TABLE = 'CLEAR_RE_STUCK_TABLE',

  // Socket Gateway
  SP_EMIT_JOIN_TABLE_EVENT = 'SP_EMIT_JOIN_TABLE_EVENT',
  SP_EMIT_START_ROUND_EVENT = 'SP_EMIT_START_ROUND_EVENT',
  SP_EMIT_LEFT_WAITING_EVENT = 'SP_EMIT_LEFT_WAITING_EVENT',
  SP_EMIT_JOIN_EXISTING_TABLE_EVENT = 'SP_EMIT_JOIN_EXISTING_TABLE_EVENT',
  SP_EMIT_DESTROY_INACTIVE_TABLE_EVENT = 'SP_EMIT_DESTROY_INACTIVE_TABLE_EVENT',
  SP_EMIT_CLEAR_QUEUE_EVENT = 'SP_EMIT_CLEAR_QUEUE_EVENT',
  SP_EMIT_END_GAME_EVENT = 'SP_EMIT_END_GAME_EVENT',
  SP_EMIT_ROUND_END_EVENT = 'SP_EMIT_ROUND_END_EVENT',
  SP_EMIT_NEXT_EVENT = 'SP_EMIT_NEXT_EVENT',
  SP_EMIT_INITIAL_BET_EVENT = 'SP_EMIT_INITIAL_BET_EVENT',
  SP_EMIT_DEAL_CARDS_EVENT = 'SP_EMIT_DEAL_CARDS_EVENT',
  SP_EMIT_LEAVE_TABLE_EVENT = 'SP_EMIT_LEAVE_TABLE_EVENT',
  SP_EMIT_GAME_ENDED_EVENT = 'SP_EMIT_GAME_ENDED_EVENT',
  SP_EMIT_END_TABLE_EVENT = 'SP_EMIT_END_TABLE_EVENT',
  SP_EMIT_REBUY_EVENT = 'SP_EMIT_REBUY_EVENT',
  SP_EMIT_PACK_EVENT = 'SP_EMIT_PACK_EVENT',
  SP_EMIT_ONLINE_USER_COUNT_EVENT = 'SP_EMIT_ONLINE_USER_COUNT_EVENT',
  SP_EMIT_HANDLE_JOIN_USER_EVENT = 'SP_EMIT_HANDLE_JOIN_USER_EVENT',
  SP_EMIT_HANDLE_LEAVE_USER_EVENT = 'SP_EMIT_HANDLE_LEAVE_USER_EVENT',

  // Socket Gateway Service
  BROADCAST_ONLINE_USER_COUNT = 'BROADCAST_ONLINE_USER_COUNT',
  SOCKET_NOTIFICATION_LUDO_TOURNAMENT = 'SOCKET_NOTIFICATION_LUDO_TOURNAMENT',
  SOCKET_NOTIFICATION_MATCH_MAKING = 'SOCKET_NOTIFICATION_MATCH_MAKING',
  GET_SP_LIVE_GAMES = 'GET_SP_LIVE_GAMES',
  CLEAR_SP_STUCK_TABLE = 'CLEAR_SP_STUCK_TABLE',
  CLEAR_CB_STUCK_TABLE = 'CLEAR_CB_STUCK_TABLE',

  // Scheduler Service
  SCHEDULE_END_GAME = 'SCHEDULE_END_GAME',
  SCHEDULE_END_ROUND = 'SCHEDULE_END_ROUND',
  SCHEDULE_START_TOURNAMENT = 'SCHEDULE_START_TOURNAMENT',
  SCHEDULE_TOURNAMENT_NOTIFIACTIONS = 'SCHEDULE_TOURNAMENT_NOTIFIACTIONS',

  // Ludo Gameply
  LUDO_END_GAME = 'LUDO_END_GAME',
  LUDO_END_ROUND = 'LUDO_END_ROUND',
  LUDO_MATCH_NORMAL_GAMES = 'LUDO_MATCH_NORMAL_GAMES',
  LUDO_TOURNAMENT_CHANGED = 'LUDO_TOURNAMENT_CHANGED',
  LUDO_TOURNAMENT_START_ROUND = 'LUDO_TOURNAMENT_START_ROUND',
  LUDO_TOURNAMENT_CANCELED = 'LUDO_TOURNAMENT_CANCELED',

  // Ludo Tournament
  LUDO_TOURNAMENT_END_ROUND = 'LUDO_TOURNAMENT_END_ROUND',
  LUDO_TOURNAMENT_END_SOME_ROUND_GAMES_EARLIER = 'LUDO_TOURNAMENT_END_SOME_ROUND_GAMES_EARLIER',
  LUDO_TOURNAMENT_IGNORE = 'LUDO_TOURNAMENT_IGNORE',
  LUDO_TOURNAMENT_CREATE = 'LUDO_TOURNAMENT_CREATE',
  LUDO_TOURNAMENT_UPDATE = 'LUDO_TOURNAMENT_UPDATE',
  LUDO_TOURNAMENT_GET_BY_ID = 'LUDO_TOURNAMENT_GET_BY_ID',
  LUDO_TOURNAMENT_GET_LIST = 'LUDO_TOURNAMENT_GET_LIST',
  LUDO_TOURNAMENT_START = 'LUDO_TOURNAMENT_START',
  LUDO_TOURNAMENT_CANCEL = 'LUDO_TOURNAMENT_CANCEL',
  LUDO_TOURNAMENT_JOIN = 'LUDO_TOURNAMENT_JOIN',
  LUDO_TOURNAMENT_GET_LEADERBOARD = 'LUDO_TOURNAMENT_GET_LEADERBOARD',
  LUDO_TOURNAMENT_GET_ROUND_INFO = 'LUDO_TOURNAMENT_GET_ROUND_INFO',
  LUDO_TOURNAMENT_GET_ROUND_PLAYERS = 'LUDO_TOURNAMENT_GET_ROUND_PLAYERS',
  LUDO_TOURNAMENT_GET_FINISHED_ROUNDS = 'LUDO_TOURNAMENT_GET_FINISHED_ROUNDS',
  LUDO_TOURNAMENT_CHECK_IF_FINISHED = 'LUDO_TOURNAMENT_CHECK_IF_FINISHED',
  LUDO_TOURNAMENT_GET_USER_STATUS = 'LUDO_TOURNAMENT_GET_USER_STATUS',
  LUDO_TOURNAMENT_GET_MY_RANK = 'LUDO_TOURNAMENT_GET_MY_RANK',

  // Ludo Mega Tournament
  LUDO_MEGA_TOURNAMENT_CREATE = 'LUDO_MEGA_TOURNAMENT_CREATE',
  LUDO_MEGA_TOURNAMENT_GET_BY_ID = 'LUDO_MEGA_TOURNAMENT_GET_BY_ID',
  LUDO_MEGA_TOURNAMENT_GET_LIST = 'LUDO_MEGA_TOURNAMENT_GET_LIST',
  LUDO_MEGA_TOURNAMENT_DEBIT_JOIN_FEE = 'LUDO_MEGA_TOURNAMENT_DEBIT_JOIN_FEE',
  LUDO_MEGA_TOURNAMENT_GET_LEADERBOARD = 'LUDO_MEGA_TOURNAMENT_GET_LEADERBOARD',
  LUDO_MEGA_TOURNAMENT_CHECK_IF_RECONNECTED = 'LUDO_MEGA_TOURNAMENT_CHECK_IF_RECONNECTED',
  LUDO_MEGA_TOURNAMENT_CREDIT_PRIZES = 'LUDO_MEGA_TOURNAMENT_CREDIT_PRIZES',
  LUDO_MEGA_TOURNAMENT_CANCEL = 'LUDO_MEGA_TOURNAMENT_CANCEL',
  LUDO_MEGA_TOURNAMENT_REFUND_JOIN_FEES = 'LUDO_MEGA_TOURNAMENT_REFUND_JOIN_FEES',
  LUDO_MEGA_TOURNAMENT_GET_HISTORY = 'LUDO_MEGA_TOURNAMENT_GET_HISTORY',

  // Snake & Ladder Game
  SL_CHECK_WALLET_BALANCE = 'SL_CHECK_WALLET_BALANCE_',
  SL_CHECK_IF_RECONNECTED = 'SL_CHECK_IF_RECONNECTED',
  GET_SL_GAME_HISTORY = 'GET_SL_GAME_HISTORY',
  GET_SL_ROUND_HISTORY = 'GET_SL_ROUND_HISTORY',
  GET_SL_LIVE_GAMES = 'GET_SL_LIVE_GAMES',
  CLEAR_SL_STUCK_TABLE = 'CLEAR_SL_STUCK_TABLE',
  SL_DEBIT_JOIN_FEE = 'SL_DEBIT_JOIN_FEE',
  EPL_DEBIT_JOIN_FEE = 'EPL_DEBIT_JOIN_FEE',
  SL_CREDIT_WIN_AMOUNT = 'SL_CREDIT_WIN_AMOUNT',
  SL_REFUND_JOIN_FEE = 'SL_REFUND_JOIN_FEE',

  // Aviator
  AVIATOR_DEBIT_BET_AMOUNT = 'AVIATOR_DEBIT_BET_AMOUNT',
  AVIATOR_CREDIT_WIN_AMOUNT = 'AVIATOR_CREDIT_WIN_AMOUNT',
  AVIATOR_CHECK_IF_RECONNECTED = 'AVIATOR_CHECK_IF_RECONNECTED',

  // EPL
  EPL_CHECK_WALLET_BALANCE = 'EPL_CHECK_WALLET_BALANCE',
}

export type TransporterMessage = {
  body: TransporterMessageBody;
  attachments?: Express.Multer.File[];
};

type TransporterMessageBody = Record<string, any>;

export type ServiceConfig = {
  host: string;
  port: number;
};

export type ServiceInfo = {
  config: ServiceConfig;
  name: TransporterProviders;
  clients: Array<App>;
};
