FROM node:20-alpine3.19

WORKDIR /root

RUN npm install --ignore-scripts -g pnpm 

EXPOSE $CBR_GAMEPLAY_SERVICE_PORT

EXPOSE $CBR_GAMEPLAY_SERVICE_PUBLIC_PORT

CMD [ "pnpm", "start:dev", "cbr-gameplay" ]
